spring:
  datasource:
      test1:
        url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456



      test2:
        url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456



